server:
  port: 8761
spring:
  application:
    name: eureka-server
  cloud:
    loadbalancer:
      ribbon:
        enabled: false
    config:
      discovery:
        enabled: true
      activate:
        on-profile: dev
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
  instance: # для localhost
        prefer-ip-address: true
        hostname: localhost