server:
  port: 8080
spring:
  application:
    name: gateway #proxy
    loadbalancer:
      ribbon:
        enabled: false
  cloud:
    gateway:
      routes:
        - id: purchase_service_route
          uri: lb://purchase-service
          predicates:
            - Path=/purchase-service/**
          filters:
            - StripPrefix=1
        - id: security_route
          uri: lb://security-service
          predicates:
            - Path=/security-service/**
          filters:
            - StripPrefix=1
eureka:
  instance: # для localhost
    prefer-ip-address: true
    hostname: localhost
logging:
  level:
    org.springframework: debug